In [2]:
a = np.arange(27)

NameError: name 'np' is not defined

In [3]:
import numpy as np

In [4]:
a = np.arange(27)

In [5]:
a = a.reshape(3,9)

In [8]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
np.split(a,(1,2))
# 1-2 2-3 3-4 4-5 와같이 잘린다!

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [11]:
np.split(a,(2,2))

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 9), dtype=int32),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [12]:
np.split(a,(-2,5))

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26]]),
 array([], shape=(0, 9), dtype=int32)]

In [13]:
np.split(a,(5,5),axis=1)

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]),
 array([], shape=(3, 0), dtype=int32),
 array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [16]:
np.hsplit(a,(5,))
# split 에 axis=1

[array([[ 0,  1,  2,  3,  4],
        [ 9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22]]), array([[ 5,  6,  7,  8],
        [14, 15, 16, 17],
        [23, 24, 25, 26]])]

In [17]:
np.vsplit(a,(2,))
# split에 axis=0

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26]])]

In [18]:
b = np.arange(5)

In [20]:
c = np.arange(5,10)

In [21]:
np.stack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
np.stack((b,c),axis=1)

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [23]:
np.vstack((b,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
np.hstack((b,c))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.r_[b,c]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.c_[b,c]

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [28]:
[1,2,3,4,5][slice(1,5)]
[1,2,3,4,5][1:5]

[2, 3, 4, 5]

In [32]:
np.arange(10)[np.s_[1]]

1

In [33]:
a = np.arange(6)

In [34]:
a

array([0, 1, 2, 3, 4, 5])

In [35]:
a[np.newaxis]

array([[0, 1, 2, 3, 4, 5]])

In [36]:
np.newaxis is None

True

In [38]:
a

array([0, 1, 2, 3, 4, 5])

In [39]:
a = a.reshape(2,3)

In [40]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
a[:,np.newaxis]

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [44]:
a[:,:,np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [45]:
a= np.arange(6)

In [47]:
a

array([0, 1, 2, 3, 4, 5])

In [46]:
a[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [48]:
np.expand_dims(a,200)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Both axis > a.ndim and axis < -a.ndim - 1 are deprecated and will raise an AxisError in the future.
  """Entry point for launching an IPython kernel.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [49]:
a

array([0, 1, 2, 3, 4, 5])

In [50]:
a = np.arange(27).reshape(3,3,3)

In [51]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [52]:
np.swapaxes(a,0,2)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [53]:
np.moveaxis(a,0,2)

array([[[ 0,  9, 18],
        [ 1, 10, 19],
        [ 2, 11, 20]],

       [[ 3, 12, 21],
        [ 4, 13, 22],
        [ 5, 14, 23]],

       [[ 6, 15, 24],
        [ 7, 16, 25],
        [ 8, 17, 26]]])

In [54]:
from collections import namedtuple

In [55]:
Address = namedtuple('Address',('name','age','weight'))

In [56]:
a1 = Address('Rex',27,81.0)

In [57]:
a1

Address(name='Rex', age=27, weight=81.0)

In [58]:
dir(a1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '_asdict',
 '_fields',
 '_fields_defaults',
 '_make',
 '_replace',
 'age',
 'count',
 'index',
 'name',
 'weight']

In [59]:
# count 와 index는 튜플에 사용되는 메소드
# 메타클래스 typed쓰면 클래스 정의 안해도 동적으로 사용가능??
# 

In [60]:
a1['name']

TypeError: tuple indices must be integers or slices, not str

In [61]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])

In [62]:
type(x)

numpy.ndarray

In [63]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__