In [4]:
from sklearn.datasets import load_iris

In [5]:
data = load_iris()

In [6]:
import pandas as pd

In [10]:
iris = pd.DataFrame(data.data, columns=data.feature_names)

In [11]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [19]:
iris_target = pd.DataFrame(data.target)

In [20]:
iris_target = pd.DataFrame(data.target, columns=['target'])

In [21]:
iris = pd.concat([iris,iris_target],axis=1)

In [22]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
5                  5.4               3.9                1.7               0.4   
6                  4.6               3.4                1.4               0.3   
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
9                  4.9               3.1                1.5               0.1   
10                 5.4               3.7                1.5               0.2   
11                 4.8               3.4                1.6               0.2   
12                 4.8               3.0                1.4               0.1   
13                 4.3               3.0                1.1               0.1   
14                 5.8               4.0                1.2               0.2   
15                 5.7               4.4                1.5               0.4   
16                 5.4               3.9                1.3               0.4   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
22                 4.6               3.6                1.0               0.2   
23                 5.1               3.3                1.7               0.5   
24                 4.8               3.4                1.9               0.2   
25                 5.0               3.0                1.6               0.2   
26                 5.0               3.4                1.6               0.4   
27                 5.2               3.5                1.5               0.2   
28                 5.2               3.4                1.4               0.2   
29                 4.7               3.2                1.6               0.2   
..                 ...               ...                ...               ...   
120                6.9               3.2                5.7               2.3   
121                5.6               2.8                4.9               2.0   
122                7.7               2.8                6.7               2.0   
123                6.3               2.7                4.9               1.8   
124                6.7               3.3                5.7               2.1   
125                7.2               3.2                6.0               1.8   
126                6.2               2.8                4.8               1.8   
127                6.1               3.0                4.9               1.8   
128                6.4               2.8                5.6               2.1   
129                7.2               3.0                5.8               1.6   
130                7.4               2.8                6.1               1.9   
131                7.9               3.8                6.4               2.0   
132                6.4               2.8                5.6               2.2   
133                6.3               2.8                5.1               1.5   
134                6.1               2.6                5.6               1.4   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4              

In [23]:
from sklearn.model_selection import train_test_split
# 트레이닝 데이터와 테스트 데이터를 쪼개줌!

In [57]:
X_train,X_test,Y_train,Y_test = train_test_split(iris.iloc[:,:-1],iris.iloc[:,-1])

In [40]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
36                 5.5               3.5                1.3               0.2
148                6.2               3.4                5.4               2.3
49                 5.0               3.3                1.4               0.2
132                6.4               2.8                5.6               2.2
66                 5.6               3.0                4.5               1.5
45                 4.8               3.0                1.4               0.3
149                5.9               3.0                5.1               1.8
104                6.5               3.0                5.8               2.2
99                 5.7               2.8                4.1               1.3
73                 6.1               2.8                4.7               1.2
143                6.8               3.2                5.9               2.3
75                 6.6               3.0                4.4               1.4
44                 5.1               3.8                1.9               0.4
83                 6.0               2.7                5.1               1.6
70                 5.9               3.2                4.8               1.8
56                 6.3               3.3                4.7               1.6
29                 4.7               3.2                1.6               0.2
136                6.3               3.4                5.6               2.4
61                 5.9               3.0                4.2               1.5
135                7.7               3.0                6.1               2.3
40                 5.0               3.5                1.3               0.3
4                  5.0               3.6                1.4               0.2
46                 5.1               3.8                1.6               0.2
123                6.3               2.7                4.9               1.8
138                6.0               3.0                4.8               1.8
7                  5.0               3.4                1.5               0.2
134                6.1               2.6                5.6               1.4
98                 5.1               2.5                3.0               1.1
31                 5.4               3.4                1.5               0.4
93                 5.0               2.3                3.3               1.0
..                 ...               ...                ...               ...
17                 5.1               3.5                1.4               0.3
113                5.7               2.5                5.0               2.0
22                 4.6               3.6                1.0               0.2
106                4.9               2.5                4.5               1.7
2                  4.7               3.2                1.3               0.2
76                 6.8               2.8                4.8               1.4
107                7.3               2.9                6.3               1.8
65                 6.7               3.1                4.4               1.4
81                 5.5               2.4                3.7               1.0
147                6.5               3.0                5.2               2.0
131                7.9               3.8                6.4               2.0
38                 4.4               3.0                1.3               0.2
30                 4.8               3.1                1.6               0.2
13                 4.3               3.0                1.1               0.1
9                  4.9               3.1                1.5               0.1
91                 6.1               3.0                4.6               1.4
116                6.5               3.0                5.5               1.8
97                 6.2               2.9                4.3               1.3
82                 5.8               2.7                3.9               1.2
87                 6.3     

In [27]:
Y_train

36     0
148    2
49     0
132    2
66     1
45     0
149    2
104    2
99     1
73     1
143    2
75     1
44     0
83     1
70     1
56     1
29     0
136    2
61     1
135    2
40     0
4      0
46     0
123    2
138    2
7      0
134    2
98     1
31     0
93     1
      ..
17     0
113    2
22     0
106    2
2      0
76     1
107    2
65     1
81     1
147    2
131    2
38     0
30     0
13     0
9      0
91     1
116    2
97     1
82     1
87     1
34     0
103    2
92     1
74     1
48     0
20     0
5      0
63     1
52     1
96     1
Name: target, Length: 112, dtype: int32

In [14]:
train = iris.sample(frac=0.75)

In [17]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
10                 5.4               3.7                1.5               0.2
11                 4.8               3.4                1.6               0.2
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
20                 5.4               3.4                1.7               0.2
21                 5.1               3.7                1.5               0.4
22                 4.6               3.6                1.0               0.2
23                 5.1               3.3                1.7               0.5
24                 4.8               3.4                1.9               0.2
25                 5.0               3.0                1.6               0.2
26                 5.0               3.4                1.6               0.4
27                 5.2               3.5                1.5               0.2
28                 5.2               3.4                1.4               0.2
29                 4.7               3.2                1.6               0.2
..                 ...               ...                ...               ...
120                6.9               3.2                5.7               2.3
121                5.6               2.8                4.9               2.0
122                7.7               2.8                6.7               2.0
123                6.3               2.7                4.9               1.8
124                6.7               3.3                5.7               2.1
125                7.2               3.2                6.0               1.8
126                6.2               2.8                4.8               1.8
127                6.1               3.0                4.9               1.8
128                6.4               2.8                5.6               2.1
129                7.2               3.0                5.8               1.6
130                7.4               2.8                6.1               1.9
131                7.9               3.8                6.4               2.0
132                6.4               2.8                5.6               2.2
133                6.3               2.8                5.1               1.5
134                6.1               2.6                5.6               1.4
135                7.7               3.0                6.1               2.3
136                6.3               3.4                5.6               2.4
137                6.4               3.1                5.5               1.8
138                6.0               3.0                4.8               1.8
139                6.9     

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
knn = KNeighborsClassifier()

In [58]:
knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [59]:
knn.predict(X_test)

array([2, 2, 2, 0, 2, 0, 2, 1, 0, 0, 0, 2, 1, 1, 2, 2, 0, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2])

In [60]:
Y_test.values

# 판다스 데이터를 넘파이로 바꾸려면 .values를 사용한다!!!

array([2, 1, 2, 0, 2, 0, 2, 1, 0, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 1, 2, 1,
       2, 0, 2, 2, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2])

In [61]:
knn.predict(X_test) == Y_test.values

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [62]:
import numpy as np

In [63]:
np.mean(knn.predict(X_test) == Y_test.values)

0.9210526315789473

In [64]:
knn.score(X_test,Y_test)

0.9210526315789473

In [65]:
from sklearn.linear_model import LogisticRegression

In [66]:
lr = LogisticRegression()

In [67]:
lr.fit(X_train,Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [68]:
lr.score(X_test,Y_test)

0.868421052631579

In [69]:
from sklearn.tree import DecisionTreeClassifier

In [70]:
tree = DecisionTreeClassifier()

In [71]:
tree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [73]:
tree.decision_path(X_test).toarray()

array([[1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0,

In [74]:
from sklearn.ensemble import RandomForestClassifier

In [77]:
rf = RandomForestClassifier()

In [78]:
rf.fit(X_train,Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [79]:
rf.feature_importances_

array([0.18766457, 0.05227148, 0.43774581, 0.32231814])

In [80]:
from sklearn.neural_network import MLPClassifier

In [81]:
from sklearn.linear_model import Perceptron

In [82]:
from sklearn.naive_bayes import GaussianNB
# 가우시안 나이브베이즈

In [83]:
from sklearn.dummy import DummyClassifier

In [84]:
dummy = DummyClassifier()

In [85]:
# 사람처럼 행동하는 classifier

In [86]:
# 다양한 알고리즘을 시행해보기 위해서 dummy가 존재

In [89]:
for i in range(1,20):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train,Y_train)
    print(i,knn.score(X_test,Y_test))

1 0.9210526315789473
2 0.9210526315789473
3 0.9210526315789473
4 0.9210526315789473
5 0.9210526315789473
6 0.9473684210526315
7 0.9473684210526315
8 0.9473684210526315
9 0.9210526315789473
10 0.9473684210526315
11 0.9473684210526315
12 0.9473684210526315
13 0.9473684210526315
14 0.9473684210526315
15 0.9473684210526315
16 0.9736842105263158
17 0.9473684210526315
18 0.9736842105263158
19 0.9736842105263158


In [90]:
from sklearn.model_selection import GridSearchCV