# NUMPY

속도를 빠르게 할려면?

GP/GPU 혹은 분산컴퓨팅


numpy 

c로 만들어짐

n개 만들어진 vectorlizaion / array 는 for 없이 연산한다!!









속도가 빠르다

복잡한 계산을 빠르고 편하게 쓰는 라이브러리



numpy는 gpu를 지원하지 않아서 tensor로 gpu를 지원하도록 만들었음

벡터를 이용해서 프로그래밍 하는 것을 vectorizaion / array programming


In [3]:
import numpy as np

In [4]:
dir(np)

# 1 인스턴스화
# literation



['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [14]:
a = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [15]:
type(a)

numpy.ndarray

In [16]:
n = np.ndarray(0)

In [17]:
n

array([], dtype=float64)

In [18]:
# 호모지니어스 
n = np.ndarray([0,'1'])

TypeError: 'str' object cannot be interpreted as an integer

In [19]:
n.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [22]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [21]:
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

c는 옆으로 저장
포트란은 밑으로 저장

size는 원소의 갯수

In [23]:
a.size

8

In [24]:
a.itemsize
# 각 하나의 원소가 몇비트 인가

4

In [28]:
a = np.array([[1,2],[3,4]])
a.dtype

dtype('int32')

In [29]:
x = [1,2,3,4,]
y= [2,3,4,5,]

x+y

[1, 2, 3, 4, 2, 3, 4, 5]

In [30]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

a+b

# 각각의 원소끼리 더해주는 기능을 수행

array([[2, 4],
       [6, 8]])

In [32]:
[i+j for i,j in zip(x,y)]

[3, 5, 7, 9]

In [33]:
a*b

array([[ 1,  4],
       [ 9, 16]])

In [34]:
a.T

array([[1, 3],
       [2, 4]])

In [35]:
a.strides

(8, 4)

In [36]:
a

array([[1, 2],
       [3, 4]])

In [38]:
b = np.array([[1,2],[3]])

In [41]:
b.strides

(8,)

numpy

c로 만들어졌고

효율적인 자료구조

호모지니어스

일렬로 저장하고 stride로 결과보여줌

In [46]:
from tensorflow.keras.dataset import mnist

ModuleNotFoundError: No module named 'tensorflow.keras.dataset'

In [45]:
!pip install tensorflow

  Stored in directory: C:\Users\jysid_000\AppData\Local\pip\Cache\wheels\5c\2e\7e\a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
  Stored in directory: C:\Users\jysid_000\AppData\Local\pip\Cache\wheels\ee\98\38\46cbcc5a93cfea5492d19c38562691ddb23b940176c14f7b48
  Stored in directory: C:\Users\jysid_000\AppData\Local\pip\Cache\wheels\7c\06\54\bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
Successfully built gast absl-py termcolor


tensorboard 1.14.0 has requirement setuptools>=41.0.0, but you'll have setuptools 40.8.0 which is incompatible.


In [47]:
_(a)

TypeError: 'tuple' object is not callable

In [49]:
len(np.sctypeDict)

152

In [50]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/P

In [51]:
a

array([[1, 2],
       [3, 4]])

In [52]:
a = np.arange(10)

In [53]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a.reshape(2,5)

# mutable함수의 결과는 3가지 변화 / 리턴 종류에 따라 3가지

s = a.reshape(2,5)

In [55]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
s

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [59]:
s.shape

(2, 5)

In [60]:
s.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [61]:
s.sum(axis=1)

array([10, 35])

In [63]:
s.sum()

45

In [64]:
import time

In [76]:
%time np.sum(np.arange(100000000))

Wall time: 283 ms


887459712

In [77]:
%time sum(range(100000000))

Wall time: 4.69 s


4999999950000000

In [81]:
a = np.zeros((3,4))

In [82]:
a = np.ones((3,4))

In [83]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [84]:
d = np.ones_like(a)

# a의 shape만 가져와서 d를 만들어줌

In [85]:
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
c = np.full((3,2),6)

In [87]:
c

array([[6, 6],
       [6, 6],
       [6, 6]])

In [91]:
e = np.eye(3)
# 단위행렬 만들기 옵션 많음!

In [92]:
c = np.identity(3)
# 단위행렬 만들기 옵션없이 빠르게

In [89]:
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
b = np.triu((3,3))

In [95]:
b

array([[3, 3],
       [0, 3]])

In [97]:
d = np.linspace(0,100)

In [98]:
d

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [99]:
e = np.logspace(1,100)

In [100]:
e

array([1.00000000e+001, 1.04811313e+003, 1.09854114e+005, 1.15139540e+007,
       1.20679264e+009, 1.26485522e+011, 1.32571137e+013, 1.38949549e+015,
       1.45634848e+017, 1.52641797e+019, 1.59985872e+021, 1.67683294e+023,
       1.75751062e+025, 1.84206997e+027, 1.93069773e+029, 2.02358965e+031,
       2.12095089e+033, 2.22299648e+035, 2.32995181e+037, 2.44205309e+039,
       2.55954792e+041, 2.68269580e+043, 2.81176870e+045, 2.94705170e+047,
       3.08884360e+049, 3.23745754e+051, 3.39322177e+053, 3.55648031e+055,
       3.72759372e+057, 3.90693994e+059, 4.09491506e+061, 4.29193426e+063,
       4.49843267e+065, 4.71486636e+067, 4.94171336e+069, 5.17947468e+071,
       5.42867544e+073, 5.68986603e+075, 5.96362332e+077, 6.25055193e+079,
       6.55128557e+081, 6.86648845e+083, 7.19685673e+085, 7.54312006e+087,
       7.90604321e+089, 8.28642773e+091, 8.68511374e+093, 9.10298178e+095,
       9.54095476e+097, 1.00000000e+100])

In [101]:
a = np.arange(10).reshape(2,5)

In [102]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [104]:
a[1][-2]

8

In [105]:
a[1,3]

8

In [106]:
a[:,3]

array([3, 8])

In [107]:
a = np.arange(27).reshape(3,3,3)

In [108]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [110]:
a[1,:]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [111]:
a[1,...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [114]:
a = np.arange(10)

In [115]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [120]:
a[[True,True,True,True,True,True,False,True,True,True]]

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

In [121]:
a = np.arange(10).reshape(5,2)

In [122]:
a[[1,3]]

array([[2, 3],
       [6, 7]])

In [123]:
b = np.nditer(a)

In [127]:
def add_(a,b):
    return a+b

In [125]:
x = np.arange(5)
y =  np.arange(5)

In [128]:
add_(x,y)

array([0, 2, 4, 6, 8])

In [129]:
x*3

array([ 0,  3,  6,  9, 12])

In [130]:
3 + np.arange(10)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

broadcasting -> numpy에서 자동으로 크기를 맞춰줌!

In [ ]:
ufunc 
universal function 
스칼라 / 벡터 어디든 지원됨 ( 범용적으로 지원되는 fucntion )

In [131]:
np.ceil([2.9,1,2,3,0.3])
# 올림함수

array([3., 1., 2., 3., 1.])

In [132]:
np.info(np.ceil)

ceil(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the ceiling of the input, element-wise.

The ceil of the scalar `x` is the smallest integer `i`, such that
`i >= x`.  It is often denoted as :math:`\lceil x \rceil`.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray or scalar
    The ceilin

In [134]:
from scipy.special import factorial

In [135]:
factorial([3,4,5])

array([  6.,  24., 120.])

In [136]:
np.info(factorial)

 factorial(n, exact=False)

The factorial of a number or array of numbers.

The factorial of non-negative integer `n` is the product of all
positive integers less than or equal to `n`::

    n! = n * (n - 1) * (n - 2) * ... * 1

Parameters
----------
n : int or array_like of ints
    Input values.  If ``n < 0``, the return value is 0.
exact : bool, optional
    If True, calculate the answer exactly using long integer arithmetic.
    If False, result is approximated in floating point rapidly using the
    `gamma` function.
    Default is False.

Returns
-------
nf : float or int or ndarray
    Factorial of `n`, as integer or float depending on `exact`.

Notes
-----
For arrays with ``exact=True``, the factorial is computed only once, for
the largest input, with each other result computed in the process.
The output dtype is increased to ``int64`` or ``object`` if necessary.

With ``exact=False`` the factorial is approximated using the gamma
function:

.. math:: n! = \Gamma(n+1)

Examples


In [137]:
b = np.arange(10)

In [138]:
np.where(b>5, 0,1)

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [139]:
np.where(b>5)

(array([6, 7, 8, 9], dtype=int64),)